75 create organism component   video list
Quran-Journey/frontend pull request #82
Opened 2024-02-02 01:46 UTC by SarahEddeb

2024-02-02 17:26 UTC, osamaramihafez requested changes

2024-02-02 17:26 UTC, osamaramihafez commented on src/components/VideoList/VideoList.tsx
> +        <VideoButtonCard
Can we actually rename video button card and video list to lesson button card and lesson list. All text relevant to that change should also be addressed. i.e. "video 1 of 12" should be "lesson 1 of 12". That I believe is inside the button card itself.

2024-02-02 21:20 UTC, SarahEddeb reviewed
Changed instances of 'video' to 'lesson'

2024-02-03 01:31 UTC, osamaramihafez approved these changes

2024-02-03 01:35 UTC, merged